_ctp_example_index:
    path:     /
    defaults: { _controller: CtpBundle:home:index }

_ctp_example:
    path:     /example/product
    defaults: { _controller: CtpBundle:Catalog:index }

_ctp_example_product:
    path:    /example/product/{slug}
    defaults: { _controller: CtpBundle:Catalog:detail }

login:
    path: /example/login
    defaults: { _controller: CtpBundle:User:login }
login_check:
    path: /example/login_check
logout:
    path: /example/logout

_ctp_example_user_details:
    path:    /example/details
    defaults: { _controller: CtpBundle:User:details }

_ctp_example_cart:
    path: /example/cart
    defaults: { _controller: CtpBundle:Cart:index}

_ctp_example_add_lineItem:
    path: /example/cart/add
    defaults: { _controller: CtpBundle:Cart:addLineItem}

_ctp_example_change_lineItem:
    path: /example/cart/change
    defaults: { _controller: CtpBundle:Cart:changeLineItem}

_ctp_example_delete_lineItem:
    path: /example/cart/delete
    defaults: { _controller: CtpBundle:Cart:deleteLineItem}

