_ctp_example_index:
    path:     /
    defaults: { _controller: CtpBundle:Home:index }

_ctp_example:
    path:     /product
    defaults: { _controller: CtpBundle:Catalog:index }

_ctp_example_product:
    path:    /product/{slug}
    defaults: { _controller: CtpBundle:Catalog:detail }

login:
    path: /login
    defaults: { _controller: CtpBundle:User:login }
login_check:
    path: /login_check
logout:
    path: /logout

_ctp_example_user_details:
    path:    /user/details
    defaults: { _controller: CtpBundle:User:details }

_ctp_example_user_address_book:
    path:    /user/address
    defaults: { _controller: CtpBundle:User:addressBook }

_ctp_example_user_address_edit:
    path:    /user/address/edit/{addressId}
    defaults: { _controller: CtpBundle:User:editAddress }

_ctp_example_cart:
    path: /cart
    defaults: { _controller: CtpBundle:Cart:index}

_ctp_example_checkout_signin:
    path: /checkout/signin
    defaults: { _controller: CtpBundle:Checkout:signin}

_ctp_example_checkout_shipping:
    path: /checkout/shipping
    defaults: { _controller: CtpBundle:Checkout:shippingMethod}

_ctp_example_checkout_address:
    path: /checkout/address
    defaults: { _controller: CtpBundle:Checkout:setAddress}

_ctp_example_checkout_confirm:
    path: /checkout/address/confirm
    defaults: { _controller: CtpBundle:Checkout:confirmation}

_ctp_example_add_lineItem:
    path: /cart/add
    defaults: { _controller: CtpBundle:Cart:addLineItem}

_ctp_example_change_lineItem:
    path: /cart/change
    defaults: { _controller: CtpBundle:Cart:changeLineItem}

_ctp_example_delete_lineItem:
    path: /cart/delete
    defaults: { _controller: CtpBundle:Cart:deleteLineItem}

_ctp_example_checkout_guest:
    path: /checkout/quest
    defaults: { _controller: CtpBundle:Checkout:setAddress}
